polar:
  catalog-service-uri: http://catalog-service

spring:
  rabbitmq:
    host: polar-rabbitmq
  r2dbc:
    url: r2dbc:postgresql://polar-postgres/polardb_order
  flyway:
    url: jdbc:postgresql://polar-postgres/polardb_order
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://polar-keycloak/realms/PolarBookshop
